name: Deploy Lambda function to AWS

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu環境で実行

    steps:
    # リポジトリをクローン
    - name: Checkout code
      uses: actions/checkout@v2

    # Python環境のセットアップ
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # 必要なライブラリのインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r RSS_FEED/python/rss_check/requirements.txt  # 修正したパス

    # Lambda関数用のzipファイルを作成
    - name: Package Lambda function (rss_check.py)
      run: |
        zip -r lambda_function.zip RSS_FEED/python/rss_check/rss_check.py  # 修正したパス

    # AWS認証の設定（GitHub SecretsにAWS認証情報を設定しておく）
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    # Lambda関数をデプロイ
    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code --function-name rss-check-rss-feed-lambda \
          --zip-file fileb://lambda_function.zip  # 関数名とzipファイルを指定
